version: "3.7"
services:
  pythonai:
    environment:
      - LANG=ja_JP.UTF-8
      - LC_CTYPE=ja_JP.utf8
    image: pythonforai
    volumes:
      - /tmp/.npm:/root/.npm
      - ./:/tmp/code
    ports:
      - 8888:8888
    working_dir: /tmp/code/
    command: sh -c "jupyter notebook \
                    --ip 0.0.0.0 \
                    --no-browser \
                    --allow-root \
                    --NotebookApp.allow_origin='https://colab.research.google.com' \
                    --port=8888 \
                    --NotebookApp.port_retries=0"
 